run drm model and visualize result
JEN6YT/HCL pull request #3
Opened 2024-11-30 18:48 UTC by JEN6YT

Pytorch implementation of drm + Visualization with 10 training epochs

2024-12-04 01:48 UTC, JEN6YT commented
percentile_barrier Implementation:

- wasn't able to test it on local or aws vm

<img width="1422" alt="Screenshot 2024-12-03 at 8 47 46 PM" src="https://github.com/user-attachments/assets/7a1ecfb2-b9c0-4e7e-8a9a-6b15941f64ae">

2024-12-20 02:43 UTC, wzoustanford requested changes
read and pls address the comments inline :)

2024-12-20 02:43 UTC, wzoustanford commented on run_script.py
> +train_treat_index = np.where(w_tr==1)[0]
This looks good. 

For good coding practice, I wonder if we can make the code shorter? 

1. could we just do e.g. nX_tr[np.where(w_tr==1)[0]]? this saves re-typing the variable 'train_treat_index' 
2. I really don't know if this is true, but have you thought about: is it easier to do indexing After converting to torch.tensor? torch may have operators (e.g. torch.where torch.index_select) that could make the notation shorter. (by indexing I mean selecting parts of the tensor with a binary mask e.g. nX_tr[train_treat_index])

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    - h_tre_rnkscore: torch.Tensor, ranker scores for treatment group.
love the comments here as documentation, it is very good practice.

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    s_tre = F.softmax(h_tre_rnkscore.squeeze(), dim=0)
[minor] squeeze removes the dim 1, but wonder where the dimension 1 is from, could we remove it upstream to make the code cleaner.

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    dc_tre = torch.sum(s_tre * c_tre)
[minor] perhaps add a 'dim=x' argument to the sum function, makes the tensor dimensions more readable.

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    obj = (dc_tre - dc_unt) / (do_tre - do_unt)
experiment with this first and see if we obtain the same graph: but should we add the 'relu' rectifier both the denominator and numerator? This ensures the operators are continuous, and the objective function is differentiable w.r.t. the parameters. (1/x is not differentiable at point x = 0)

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    # Optional differentiable version:
it's here, supposed this line was tried in the experiment?

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    optimizer = Adam(model.parameters(), lr=lr)
Optimizer should also be defined only once, then used at each iteration. 

For code readability, I'd suggest remove the 'optimize_model' function, since it confuses readers to consider initializing the optimizer inside it due to its name, also you'd have to document its argument while it only wraps 3-5 lines.

2024-12-20 02:43 UTC, wzoustanford commented on Model/drm.py
> +    optimizer.step()
this line, if I understand correctly, only takes 1 gradient step.

2024-12-20 02:43 UTC, wzoustanford commented on run_script.py
> +for epoch in range(drm_epochs):
if I understand correctly, the code here only implements 10 gradient steps of Adam. 

- let's run it for longer, print out the loss to ensure it converges (run to the point where loss value change is small across steps) 
- only for clarification, 'epoch' is commonly used in mini-batch or stochastic gradient descent, to indicate running enough data points to cover the entire dataset. It's not ill-used here, since each step uses the entire dataset, it's just more commonly used in mini-batch settings. 'for step in range(drm_steps)' would also be OK here.

2024-12-20 02:53 UTC, JEN6YT commented on Model/drm.py
> +    optimizer = Adam(model.parameters(), lr=lr)
Optimizer initialization.
Zero-grad

for
   obj
   backward
   step

2025-01-14 00:45 UTC, wzoustanford commented
Has this problem been fixed? I'm guessing it is, since we already saw curves from the PB method. If so, feel free to reply to or close the comment. 

> percentile_barrier Implementation:
> 
> * wasn't able to test it on local or aws vm
> 
> <img alt="Screenshot 2024-12-03 at 8 47 46 PM" width="1422" src="https://private-user-images.githubusercontent.com/71663327/392195405-7a1ecfb2-b9c0-4e7e-8a9a-6b15941f64ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MTU3MzIsIm5iZiI6MTczNjgxNTQzMiwicGF0aCI6Ii83MTY2MzMyNy8zOTIxOTU0MDUtN2ExZWNmYjItYjljMC00ZTdlLThhOWEtNmIxNTk0MWY2NGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDAwNDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlY2RiOGFiY2VjOTAyNjgzZDRmYTE0ZTdlNTE0ZDA0ZjZlOWExZDdjOWE1MGYyNzFiNWUzMzljMWM4ODJjYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sDKZ0EyaFAwgKvleQJs2rduU16puN5piSXNK8YZo6UI">

2025-01-14 00:46 UTC, wzoustanford commented on run_script.py
> +for epoch in range(drm_epochs):
@JEN6YT has this problem (only 10 gradient steps, and grad is zeroed every iteration) fixed? Is this same code logic used to run the two latest experiment curves. 

It's important to fix this optimization problem before comparing results. 

It's going to affect DRM and PB methods a lot.

2025-01-14 00:50 UTC, wzoustanford commented on run_script.py
> +train_treat_index = np.where(w_tr==1)[0]
Code quality is as important as getting results :) pls address this. 

You'll see that once the code base gets larger, the code and parameters are going to be messy. Engineering practices to make it readable and systematic, come first.

2025-01-14 00:57 UTC, wzoustanford commented on run_script.py
> +for epoch in range(drm_epochs):
the fix is in this commit: https://github.com/JEN6YT/HCL/pull/3/commits/a62569fbf9878d87779e91cd761485512d1d975c

2025-01-14 00:59 UTC, wzoustanford commented on Model/drm.py
> +    obj = (dc_tre - dc_unt) / (do_tre - do_unt)
fixed in commit: https://github.com/JEN6YT/HCL/pull/3/commits/a62569fbf9878d87779e91cd761485512d1d975c

2025-01-14 00:59 UTC, merged